### ISSUE TITLE
HW06,Task4 results

### ISSUE THREAD

**Issue by shihwachang** [ccsf-math-108/materials-fa23#27]
When I attempted to code the results, it returns array of ([1,1,0,......]), then I need to use bool_arr to convert it to the boolean values that we were asked to do. Is this the intended task?

<img width="643" alt="Screen Shot 2023-10-04 at 7 34 11 AM" src="https://github.com/ccsf-math-108/materials-fa23/assets/145944014/1ece63cd-397e-4c77-b0dd-406ef35e3189">

**Comment by shawnwiggins** [comment]
I'm not sure what `bool_arr` is since you just commented out the name in the image. The hint suggests that you should use the `apply` table method for the intended solution. This is how you can prevent looping through the row indexes.

_I don't see anything to fix, so I'll close this issue. It seems this is more of a question about the intended way to complete the assignment._
