### ISSUE TITLE
HW 12, task 2 and task 10 contains the same "correlation" function, yet defined differently

### ISSUE THREAD

**Issue by shihwachang** [ccsf-math-108/materials-fa23#56]
This results in error in the final auto grading function. I suggest change the task 2 "correlation" to a different name( such as "correlation coefficient" )with a change on its auto grading, since it involves less of subsequent usage than task 10.

**Comment by shawnwiggins** [comment]
@shihwachang, good catch! I'll fix that now by using `correlation_coefficient` as the name of the function you create in Task 02. Additionally, I'll remove the redundant task that asks you to re-create the `standard_units` function in Part 1 of Task 10.

**Comment by shawnwiggins** [comment]
# Steps
- [ ] Update the function name from `correlation` to `correlation_coefficient` in Task 02. (This impacts Task 05 since it is assumed that students will need to use the function from Task 02.)
- [ ] Update the instructions for Task 10 to prevent students from recreating the `standard_units` function.
- [ ] Update the instructions for Task 10 to have students create a new correlation function called `correlation`. 
- [ ] Provide a note in Task 10 to use the `standard_units` function from Task 01 to create `correlation`.

**Comment by shawnwiggins** [comment]
The changes were made, but I'll leave this issue open until the assignment deadline for reference.
